### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by bluenevus** [rtc-io/demo-screenshare#3]
I went to rtc.io/screeny to check out the demo.  It asked me for an extension which I installed.  It then popped up a screen that allowed me to share my screen and generated a url.  I could see the chrome screen share widget running at the bottom of the shared screen.  However, when I share the url with someone else...it simply hangs on a black screen or sometimes mentioning that its trying to connect but never actually shares the screen.

**Comment by DamonOehlman** [comment]
Thanks for reporting this - I'll take a look and see if I can find out what is going on.

**Comment by bluenevus** [comment]
Appreciate any insight into this.  I would love to use the product.

Vr,
Frank

**Comment by silviapfeiffer** [comment]
I've just tested it and if you use https, it actually works: https://rtc.io/screeny/
